/*
 * FormNetCalc.java
 *
 * Created on 03/06/2009, 10:24:07
 */

package netcalc;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FormNetCalc extends javax.swing.JFrame {

    private NetCalc nc = new NetCalc();
    private boolean busy = true;

    private String decimalFormat = "#,###,###,###";

    private void initNet() {
        busy = true;

        setNetAddress();

        DecimalFormat df = new DecimalFormat(decimalFormat);

        for (int i = 0; i <= nc.getBits(); i++) {
            cmbNetBits.addItem(String.valueOf(i));
            cmbHostBits.addItem(String.valueOf(i));
            cmbNets.addItem(df.format(Math.pow(2, i)));
            cmbHosts.addItem(df.format(Math.pow(2, i)));
        }
        busy = false;

        setNetBits();
    }

    private void initSubNet() {
        busy = true;

        cmbSubNetBits.removeAllItems();
        cmbSubHostBits.removeAllItems();
        cmbSubNets.removeAllItems();
        cmbSubHosts.removeAllItems();

        DecimalFormat df = new DecimalFormat();

        for (int i = 0; i <= nc.getHostBits(); i++) {
            cmbSubNetBits.addItem(String.valueOf(i));
            cmbSubHostBits.addItem(String.valueOf(i));
            cmbSubNets.addItem(df.format(Math.pow(2, i)));
            cmbSubHosts.addItem(df.format(Math.pow(2, i)));
        }
        busy = false;

        cmbSubNetBitsActionPerformed(null);
    }

    private long getComboInt(JComboBox c) {
        DecimalFormat df = new DecimalFormat(decimalFormat);

        Number n = null;
        try {
            n = df.parse(String.valueOf(c.getSelectedItem()));
        } catch (ParseException e) {
        }
        
        return n.longValue();
    }
    private long getComboIntAt(JComboBox c, int i) {
        DecimalFormat df = new DecimalFormat(decimalFormat);

        Number n = null;
        try {
            n = df.parse(String.valueOf(c.getItemAt(i)));
        } catch (ParseException e) {
        }

        return n.longValue();
    }
    private void setComboInt(JComboBox c, long value) {
        for(int i = 0; i < c.getItemCount(); i++) {
            if (value == getComboIntAt(c, i)) {
                c.setSelectedIndex(i);
                break;
            }
        }
    }

    private void setNetAddress() {
        txtNetAddress.setText(nc.getNetAddress());
    }
    private void setNetBits() {
        setComboInt(cmbNetBits, nc.getNetBits());
    }
    private void setHostBits() {
        setComboInt(cmbHostBits, nc.getHostBits());
    }
    private void setNets() {
        setComboInt(cmbNets, nc.getNets());
    }
    private void setHosts() {
        setComboInt(cmbHosts, nc.getHosts());
    }
    private void setNetMask() {
        txtNetMask.setText(nc.getNetMask());
    }

    private void setSubNetBits() {
        setComboInt(cmbSubNetBits, nc.getSubNetBits());
    }
    private void setSubHostBits() {
        setComboInt(cmbSubHostBits, nc.getSubHostBits());
    }
    private void setSubNets() {
        setComboInt(cmbSubNets, nc.getSubNets());
    }
    private void setSubHosts() {
        setComboInt(cmbSubHosts, nc.getSubHosts());
    }
    private void setSubNetMask() {
        txtSubNetMask.setText(nc.getSubNetMask());
    }
    private void setSubNetsList() {
        DefaultTableModel m = (DefaultTableModel)tabSubNets.getModel();
        for (int i = m.getRowCount() - 1; i >= 0; i--)
            m.removeRow(i);

        List l = nc.getSubNetsList();
        for (int i = 0; i < l.size(); i++)
            m.addRow((String[])l.get(i));
    }

    /** Creates new form FormNetCalc */
    public FormNetCalc() {
        initComponents();

        initNet();

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        setLocation((d.width - this.getWidth()) / 2, (d.height - this.getHeight()) / 2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    DialogAbout = new javax.swing.JDialog();
    jPanel3 = new javax.swing.JPanel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    jButton2 = new javax.swing.JButton();
    jLabel15 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    cmbNetBits = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    cmbHostBits = new javax.swing.JComboBox();
    jLabel3 = new javax.swing.JLabel();
    cmbNets = new javax.swing.JComboBox();
    jLabel4 = new javax.swing.JLabel();
    cmbHosts = new javax.swing.JComboBox();
    jLabel5 = new javax.swing.JLabel();
    txtNetMask = new javax.swing.JTextField();
    jLabel16 = new javax.swing.JLabel();
    btnNetAddress = new javax.swing.JButton();
    txtNetAddress = new javax.swing.JTextField();
    btnAbout = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    cmbSubNetBits = new javax.swing.JComboBox();
    cmbSubHostBits = new javax.swing.JComboBox();
    cmbSubNets = new javax.swing.JComboBox();
    cmbSubHosts = new javax.swing.JComboBox();
    jLabel14 = new javax.swing.JLabel();
    txtSubNetMask = new javax.swing.JTextField();
    jPanel5 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tabSubNets = new javax.swing.JTable();

    DialogAbout.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    DialogAbout.setTitle("Sobre...");
    DialogAbout.setModal(true);
    DialogAbout.setResizable(false);

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

    jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getStyle() | java.awt.Font.BOLD, jLabel10.getFont().getSize()+2));
    jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel10.setText("NetCalc");

    jLabel11.setText("Desenvolvido por Fabio Agostinho Boris");

    jLabel12.setText("http://www.fabioboris.com");

    jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel13.setText("Criado em 3 de Junho de 2009");

    jButton2.setText("Fechar");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel4.add(jButton2);

    jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel15.setText("Última atualização em 8 de Junho de 2009");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
          .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
          .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
          .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
          .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
          .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addComponent(jLabel10)
        .addGap(18, 18, 18)
        .addComponent(jLabel13)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel15)
        .addGap(18, 18, 18)
        .addComponent(jLabel11)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel12)
        .addGap(18, 18, 18)
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout DialogAboutLayout = new javax.swing.GroupLayout(DialogAbout.getContentPane());
    DialogAbout.getContentPane().setLayout(DialogAboutLayout);
    DialogAboutLayout.setHorizontalGroup(
      DialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(DialogAboutLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    DialogAboutLayout.setVerticalGroup(
      DialogAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(DialogAboutLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(14, Short.MAX_VALUE))
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("NetCalc");
    setBounds(new java.awt.Rectangle(64, 64, 0, 0));
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setPreferredSize(null);
    setResizable(false);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Redes"));

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setText("Bits do prefixo:");
    jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jLabel1.setMaximumSize(new java.awt.Dimension(40, 0));
    jLabel1.setMinimumSize(new java.awt.Dimension(40, 0));
    jLabel1.setPreferredSize(new java.awt.Dimension(40, 14));

    cmbNetBits.setPreferredSize(new java.awt.Dimension(120, 20));
    cmbNetBits.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbNetBitsActionPerformed(evt);
      }
    });

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("Bits do sufixo:");
    jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jLabel2.setMaximumSize(new java.awt.Dimension(40, 0));
    jLabel2.setMinimumSize(new java.awt.Dimension(40, 0));
    jLabel2.setPreferredSize(new java.awt.Dimension(40, 14));

    cmbHostBits.setPreferredSize(new java.awt.Dimension(120, 20));
    cmbHostBits.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbHostBitsActionPerformed(evt);
      }
    });

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("Endereços de rede:");
    jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jLabel3.setMaximumSize(new java.awt.Dimension(40, 0));
    jLabel3.setMinimumSize(new java.awt.Dimension(40, 0));
    jLabel3.setPreferredSize(new java.awt.Dimension(40, 14));

    cmbNets.setPreferredSize(new java.awt.Dimension(120, 20));
    cmbNets.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbNetsActionPerformed(evt);
      }
    });

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText("Endereços por rede:");
    jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jLabel4.setMaximumSize(new java.awt.Dimension(40, 0));
    jLabel4.setMinimumSize(new java.awt.Dimension(40, 0));
    jLabel4.setPreferredSize(new java.awt.Dimension(40, 14));

    cmbHosts.setPreferredSize(new java.awt.Dimension(120, 20));
    cmbHosts.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbHostsActionPerformed(evt);
      }
    });

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel5.setText("Máscara de rede:");
    jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jLabel5.setMaximumSize(new java.awt.Dimension(40, 0));
    jLabel5.setMinimumSize(new java.awt.Dimension(40, 0));
    jLabel5.setPreferredSize(new java.awt.Dimension(40, 14));

    txtNetMask.setEditable(false);

    jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel16.setText("Endereço de rede:");
    jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jLabel16.setMaximumSize(new java.awt.Dimension(40, 0));
    jLabel16.setMinimumSize(new java.awt.Dimension(40, 0));
    jLabel16.setPreferredSize(new java.awt.Dimension(40, 14));

    btnNetAddress.setText("...");
    btnNetAddress.setToolTipText("Alterar endereço de rede");
    btnNetAddress.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNetAddressActionPerformed(evt);
      }
    });

    txtNetAddress.setEditable(false);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(cmbNetBits, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(cmbHostBits, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(cmbNets, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(cmbHosts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(txtNetMask)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtNetAddress)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnNetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnNetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtNetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cmbNetBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbHostBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbNets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbHosts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtNetMask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    btnAbout.setText("Sobre...");
    btnAbout.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAboutActionPerformed(evt);
      }
    });

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sub-Redes"));

    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel6.setText("Endereços por sub-rede:");
    jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jLabel6.setPreferredSize(new java.awt.Dimension(40, 14));

    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel7.setText("Endereços de sub-rede:");
    jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jLabel7.setPreferredSize(new java.awt.Dimension(40, 14));

    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel8.setText("Bits do sufixo:");
    jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jLabel8.setPreferredSize(new java.awt.Dimension(40, 14));

    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel9.setText("Bits do prefixo:");
    jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jLabel9.setPreferredSize(new java.awt.Dimension(40, 14));

    cmbSubNetBits.setPreferredSize(new java.awt.Dimension(120, 20));
    cmbSubNetBits.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbSubNetBitsActionPerformed(evt);
      }
    });

    cmbSubHostBits.setPreferredSize(new java.awt.Dimension(120, 20));
    cmbSubHostBits.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbSubHostBitsActionPerformed(evt);
      }
    });

    cmbSubNets.setPreferredSize(new java.awt.Dimension(120, 20));
    cmbSubNets.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbSubNetsActionPerformed(evt);
      }
    });

    cmbSubHosts.setPreferredSize(new java.awt.Dimension(120, 20));
    cmbSubHosts.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cmbSubHostsActionPerformed(evt);
      }
    });

    jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel14.setText("Máscara de sub-rede:");
    jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    jLabel14.setPreferredSize(new java.awt.Dimension(40, 14));

    txtSubNetMask.setEditable(false);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(cmbSubNetBits, javax.swing.GroupLayout.Alignment.TRAILING, 0, 140, Short.MAX_VALUE)
              .addComponent(cmbSubHostBits, 0, 140, Short.MAX_VALUE)
              .addComponent(cmbSubNets, 0, 140, Short.MAX_VALUE)
              .addComponent(cmbSubHosts, 0, 140, Short.MAX_VALUE)))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtSubNetMask, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cmbSubNetBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbSubHostBits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbSubNets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbSubHosts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtSubNetMask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de sub-redes"));

    tabSubNets.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Rede", "Broadcast"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(tabSubNets);

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(btnAbout, javax.swing.GroupLayout.Alignment.TRAILING))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnAbout))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void cmbNetBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNetBitsActionPerformed
        if (!busy) {
            busy = true;
            nc.setNetBits((int)getComboInt(cmbNetBits));
            setHostBits();
            setNets();
            setHosts();
            setNetMask();
            busy = false;
            initSubNet();
        }
    }//GEN-LAST:event_cmbNetBitsActionPerformed

    private void cmbHostBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHostBitsActionPerformed
        if (!busy) {
            busy = true;
            nc.setHostBits((int)getComboInt(cmbHostBits));
            setNetBits();
            setHosts();
            setNets();
            setNetMask();
            busy = false;
            initSubNet();
        }
    }//GEN-LAST:event_cmbHostBitsActionPerformed

    private void cmbNetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNetsActionPerformed
        if (!busy) {
            busy = true;
            nc.setNets((int)getComboInt(cmbNets));
            setNetBits();
            setHosts();
            setHostBits();
            setNetMask();
            busy = false;
            initSubNet();
        }
    }//GEN-LAST:event_cmbNetsActionPerformed

    private void cmbHostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHostsActionPerformed
        if (!busy) {
            busy = true;
            nc.setHosts((int)getComboInt(cmbHosts));
            setHostBits();
            setNets();
            setNetBits();
            setNetMask();
            busy = false;
            initSubNet();
        }
    }//GEN-LAST:event_cmbHostsActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        DialogAbout.pack();

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        DialogAbout.setLocation((d.width - DialogAbout.getWidth()) / 2, (d.height - DialogAbout.getHeight()) / 2);

        DialogAbout.setVisible(true);
}//GEN-LAST:event_btnAboutActionPerformed

    private void cmbSubNetBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSubNetBitsActionPerformed
        if (!busy) {
            busy = true;
            nc.setSubNetBits((int)getComboInt(cmbSubNetBits));
            setSubHostBits();
            setSubNets();
            setSubHosts();
            setSubNetMask();
            setSubNetsList();
            busy = false;
        }
}//GEN-LAST:event_cmbSubNetBitsActionPerformed

    private void cmbSubHostBitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSubHostBitsActionPerformed
        if (!busy) {
            busy = true;
            nc.setSubHostBits((int)getComboInt(cmbSubHostBits));
            setSubNetBits();
            setSubHosts();
            setSubNets();
            setSubNetMask();
            setSubNetsList();
            busy = false;
        }
}//GEN-LAST:event_cmbSubHostBitsActionPerformed

    private void cmbSubNetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSubNetsActionPerformed
        if (!busy) {
            busy = true;
            nc.setSubNets((int)getComboInt(cmbSubNets));
            setSubNetBits();
            setSubHosts();
            setSubHostBits();
            setSubNetMask();
            setSubNetsList();
            busy = false;
        }
}//GEN-LAST:event_cmbSubNetsActionPerformed

    private void cmbSubHostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSubHostsActionPerformed
        if (!busy) {
            busy = true;
            nc.setSubHosts((int)getComboInt(cmbSubHosts));
            setSubHostBits();
            setSubNets();
            setSubNetBits();
            setSubNetMask();
            setSubNetsList();
            busy = false;
        }
}//GEN-LAST:event_cmbSubHostsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DialogAbout.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    private void btnNetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetAddressActionPerformed
        String s = JOptionPane.showInputDialog("Digite o endereço de rede", nc.getNetAddress());
        if (s != null) {
            try {
                nc.setNetAddress(s);
            }
            catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, "Endereço de rede inválido", "Atenção!", JOptionPane.ERROR_MESSAGE);
            }
            finally {
                setNetAddress();
                setSubNetsList();
            }
        }
}//GEN-LAST:event_btnNetAddressActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNetCalc().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JDialog DialogAbout;
  private javax.swing.JButton btnAbout;
  private javax.swing.JButton btnNetAddress;
  private javax.swing.JComboBox cmbHostBits;
  private javax.swing.JComboBox cmbHosts;
  private javax.swing.JComboBox cmbNetBits;
  private javax.swing.JComboBox cmbNets;
  private javax.swing.JComboBox cmbSubHostBits;
  private javax.swing.JComboBox cmbSubHosts;
  private javax.swing.JComboBox cmbSubNetBits;
  private javax.swing.JComboBox cmbSubNets;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tabSubNets;
  private javax.swing.JTextField txtNetAddress;
  private javax.swing.JTextField txtNetMask;
  private javax.swing.JTextField txtSubNetMask;
  // End of variables declaration//GEN-END:variables

}
